/**
 * Enrichment pipeline: data/<dataset>/latin.tsv → data/<dataset>/entries.json
 * plus enrichment-review.md flagging rows that need human review/overrides.
 *
 * Override files (data/<dataset>/overrides/<id>.json) are shallow-merged over
 * the parsed entry; `flags` are unioned. An override may also carry a `forms`
 * key (hand-written paradigm) consumed later by generate-forms.ts.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { normalizeOrthography, parseRow } from './lib/enrich-core'
import type { VocabEntry } from '../src/lib/dataset/types'

const datasetId = process.argv.includes('--dataset')
  ? process.argv[process.argv.indexOf('--dataset') + 1]
  : 'knudsvig-731'

const dataDir = join(import.meta.dirname, '..', 'data', datasetId)
const tsvPath = join(dataDir, 'latin.tsv')
const overridesDir = join(dataDir, 'overrides')

const slug = (s: string) =>
  s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, '')

const lines = readFileSync(tsvPath, 'utf8').split('\n').map((l) => l.trim()).filter(Boolean)
const header = lines[0].toLowerCase().startsWith('dict') || lines[0].toLowerCase().startsWith('form') ? 1 : 0

const entries: VocabEntry[] = []
const idCounts = new Map<string, number>()
const skipped: string[] = []

for (const line of lines.slice(header)) {
  const [rawDict, def, chap] = line.split('\t').map((c) => (c ?? '').trim())
  if (!rawDict) continue
  const dict = normalizeOrthography(rawDict)
  const parsed = parseRow(dict, def ?? '', chap ?? '')
  if (parsed.chapter === 0) {
    skipped.push(dict)
    continue
  }
  let id = `${slug(parsed.lemma)}-${parsed.pos}`
  const n = (idCounts.get(id) ?? 0) + 1
  idCounts.set(id, n)
  if (n > 1) id = `${id}-${n}`
  entries.push({ id, ...parsed })
}

// apply overrides
let overrideCount = 0
if (existsSync(overridesDir)) {
  for (const f of readdirSync(overridesDir).filter((f) => f.endsWith('.json'))) {
    const id = f.replace(/\.json$/, '')
    const entry = entries.find((e) => e.id === id)
    if (!entry) {
      console.warn(`override ${f}: no entry with id "${id}"`)
      continue
    }
    const patch = JSON.parse(readFileSync(join(overridesDir, f), 'utf8'))
    const { forms: _forms, flags: patchFlags, ...rest } = patch
    Object.assign(entry, rest)
    if (patchFlags) entry.flags = [...new Set([...entry.flags, ...patchFlags])]
    entry.morphOverride = f
    overrideCount++
  }
}

writeFileSync(join(dataDir, 'entries.json'), JSON.stringify(entries, null, 1))

// ── review report ────────────────────────────────────────────────────────────
const byPos = new Map<string, number>()
for (const e of entries) byPos.set(e.pos, (byPos.get(e.pos) ?? 0) + 1)

const section = (title: string, items: VocabEntry[], detail: (e: VocabEntry) => string = (e) => e.dict) =>
  items.length
    ? `\n## ${title} (${items.length})\n\n${items.map((e) => `- \`${e.id}\` — ${detail(e)}`).join('\n')}\n`
    : ''

const report = `# Enrichment review — ${datasetId}

Generated by scripts/enrich.ts. Fix entries by adding \`overrides/<id>.json\`
(fields shallow-merge; \`flags\` union; optional \`forms\` for a hand-written paradigm).

## Counts

- entries: ${entries.length} (skipped, no chapter: ${skipped.length})
- overrides applied: ${overrideCount}
${[...byPos.entries()].sort((a, b) => b[1] - a[1]).map(([p, c]) => `- ${p}: ${c}`).join('\n')}
${section('Unclassified (pos=other) — need overrides', entries.filter((e) => e.pos === 'other'), (e) => `${e.dict} — ${e.definition}`)}${section('Phrases (no forms generated)', entries.filter((e) => e.pos === 'phrase'), (e) => `${e.dict} — ${e.definition}`)}${section('i-stem candidates — confirm with `"flags": ["i-stem"]` or dismiss with `"flags": ["not-i-stem"]`', entries.filter((e) => e.flags.includes('i-stem?')))}${section('Irregular verbs — verify engine/override coverage', entries.filter((e) => e.pos === 'v' && e.flags.includes('irreg')))}${section('Deponent verbs', entries.filter((e) => e.flags.includes('deponent')))}${section('Semi-deponent verbs', entries.filter((e) => e.flags.includes('semi-deponent')))}${section('Plural-only nouns', entries.filter((e) => e.flags.includes('plural-only')))}${section('Alternate citation forms', entries.filter((e) => e.flags.includes('alt-forms')))}${section('Pronouns', entries.filter((e) => e.pos === 'pron'))}${section('Dict strings with unconsumed parentheses', entries.filter((e) => /\(/.test(e.dict) && !e.flags.includes('1term') && e.pos !== 'other'))}${skipped.length ? `\n## Skipped rows (no parseable chapter)\n\n${skipped.map((s) => `- ${s}`).join('\n')}\n` : ''}`

if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true })
writeFileSync(join(dataDir, 'enrichment-review.md'), report)

console.log(`entries: ${entries.length}, overrides: ${overrideCount}, skipped: ${skipped.length}`)
console.log([...byPos.entries()].sort((a, b) => b[1] - a[1]).map(([p, c]) => `${p}:${c}`).join(' '))
